packages = [
  "emacs-pgtk",
  "git",
  "cmatrix",
  "python3",
  "alacritty",
  "go",
  "nautilus",
  "typst",
  "xwayland-satellite",
  "stow",
  "vim",
  "zellij",
  "opencode",
  "neovim",
  "htop",
  "fastfetch",
  "nodejs",
  "lazygit",
  "ripgrep",
  "tree-sitter",
  "qmk",
  "fuzzel",
  "gcc"
]

flatpaks = [
  "app.zen_browser.zen",
  "org.onlyoffice.desktopeditors",
  "net.lutris.Lutris",
  "com.discordapp.Discord",
  "org.jamovi.jamovi"
]
