packages = [
  "emacs-pgtk",
  "git",
  "cmatrix",
  "python3",
  "alacritty",
  "go",
  "nautilus",
  "typst",
  "xwayland-satellite",
  "stow",
  "vim",
  "zellij",
  "opencode",
  "neovim",
  "htop",
  "fastfetch"
]

flatpaks = [
  "app.zen_browser.zen",
  "org.onlyoffice.desktopeditors"
]
