packages = [
  "emacs-pgtk",
  "git",
  "cmatrix",
  "python3",
  "cosmic-term",
  "go",
  "nautilus",
  "typst",
  "xwayland-satellite",
  "stow"
]

flatpaks = [
  "app.zen_browser.zen",
  "org.onlyoffice.desktopeditors"
]
